#!/bin/bash

source /home/kelaun/.config/dmenu/.dmenurc

selection=`echo -e $(lpass ls | awk -F '[/[]' '{print $(NF-1)"\\\n"}' | sort) | dmenu $DMENU_OPTIONS`

if [ "$selection" != "" ]; then
    lpass show -c --password $selection &
fi
