#!/usr/bin/env python
import subprocess

BOLD = '\033[1m'
END = '\033[0m'

distro = "Arch Linux"
kernel = 'linux '+subprocess.getoutput('uname --kernel-release')
wm = "spectrwm" 
uptime = subprocess.getoutput('uptime -p | sed "s/up //g" | sed "s/,/ and/g"')
shell = "bash"


print('''         /\           ''')
print('''        /  \          {}'''.format(BOLD+"\tdistro: "+END+distro))
print('''       /\   \         {}'''.format(BOLD+"\tkernel: "+END+kernel))
print('''      /  __  \        {}'''.format(BOLD+"\twm:     "+END+wm))
print('''     /  (  )  \       {}'''.format(BOLD+"\tuptime: "+END+uptime))
print('''    / __|  |__\\\\    {}'''.format(BOLD+"\tshell:  "+END+shell))
print('''   /.`        `.\   \n''')
